
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ARQUIVO BARRAS CALCULAR CARREGAR COLUNA COM COMO DA DADOS DE E EIXO_X EIXO_Y GRAFICO ID LINHAS MEDIA MEDIANA MODA MOSTRAR PLOTAR SALVAR STRING\nprograma : comando\n         | programa comando\ncomando : MOSTRAR DADOS DE IDcomando : CARREGAR DADOS DE STRING COMO IDcomando : CALCULAR tipo_calculo DA COLUNA STRING DE IDtipo_calculo : MEDIAtipo_calculo : MEDIANAtipo_calculo : MODA\ncomando : PLOTAR GRAFICO DE tipo_grafico COM EIXO_X STRING E EIXO_Y STRING DE ID SALVAR COMO STRING\n        | PLOTAR GRAFICO DE tipo_grafico COM EIXO_X STRING E EIXO_Y STRING DE ID\ncomando : CARREGAR ARQUIVO COMO IDtipo_grafico : BARRAStipo_grafico : LINHAS'
    
_lr_action_items = {'MOSTRAR':([0,1,2,7,21,23,31,34,40,43,],[3,3,-1,-2,-3,-11,-4,-5,-10,-9,]),'CARREGAR':([0,1,2,7,21,23,31,34,40,43,],[4,4,-1,-2,-3,-11,-4,-5,-10,-9,]),'CALCULAR':([0,1,2,7,21,23,31,34,40,43,],[5,5,-1,-2,-3,-11,-4,-5,-10,-9,]),'PLOTAR':([0,1,2,7,21,23,31,34,40,43,],[6,6,-1,-2,-3,-11,-4,-5,-10,-9,]),'$end':([1,2,7,21,23,31,34,40,43,],[0,-1,-2,-3,-11,-4,-5,-10,-9,]),'DADOS':([3,4,],[8,9,]),'ARQUIVO':([4,],[10,]),'MEDIA':([5,],[12,]),'MEDIANA':([5,],[13,]),'MODA':([5,],[14,]),'GRAFICO':([6,],[15,]),'DE':([8,9,15,29,38,],[16,17,20,32,39,]),'COMO':([10,22,41,],[18,28,42,]),'DA':([11,12,13,14,],[19,-6,-7,-8,]),'ID':([16,18,28,32,39,],[21,23,31,34,40,]),'STRING':([17,24,33,37,42,],[22,29,35,38,43,]),'COLUNA':([19,],[24,]),'BARRAS':([20,],[26,]),'LINHAS':([20,],[27,]),'COM':([25,26,27,],[30,-12,-13,]),'EIXO_X':([30,],[33,]),'E':([35,],[36,]),'EIXO_Y':([36,],[37,]),'SALVAR':([40,],[41,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'programa':([0,],[1,]),'comando':([0,1,],[2,7,]),'tipo_calculo':([5,],[11,]),'tipo_grafico':([20,],[25,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> programa","S'",1,None,None,None),
  ('programa -> comando','programa',1,'p_programa','graficalc_engine.py',63),
  ('programa -> programa comando','programa',2,'p_programa','graficalc_engine.py',64),
  ('comando -> MOSTRAR DADOS DE ID','comando',4,'p_comando_mostrar','graficalc_engine.py',69),
  ('comando -> CARREGAR DADOS DE STRING COMO ID','comando',6,'p_comando_carregar','graficalc_engine.py',98),
  ('comando -> CALCULAR tipo_calculo DA COLUNA STRING DE ID','comando',7,'p_comando_calcular','graficalc_engine.py',121),
  ('tipo_calculo -> MEDIA','tipo_calculo',1,'p_tipo_calculo_media','graficalc_engine.py',157),
  ('tipo_calculo -> MEDIANA','tipo_calculo',1,'p_tipo_calculo_mediana','graficalc_engine.py',161),
  ('tipo_calculo -> MODA','tipo_calculo',1,'p_tipo_calculo_moda','graficalc_engine.py',165),
  ('comando -> PLOTAR GRAFICO DE tipo_grafico COM EIXO_X STRING E EIXO_Y STRING DE ID SALVAR COMO STRING','comando',15,'p_comando_plotar','graficalc_engine.py',170),
  ('comando -> PLOTAR GRAFICO DE tipo_grafico COM EIXO_X STRING E EIXO_Y STRING DE ID','comando',12,'p_comando_plotar','graficalc_engine.py',171),
  ('comando -> CARREGAR ARQUIVO COMO ID','comando',4,'p_comando_carregar_arquivo','graficalc_engine.py',228),
  ('tipo_grafico -> BARRAS','tipo_grafico',1,'p_tipo_grafico_barras','graficalc_engine.py',258),
  ('tipo_grafico -> LINHAS','tipo_grafico',1,'p_tipo_grafico_linhas','graficalc_engine.py',262),
]
